### ISSUE TITLE
Problèmes d'erreurs quand on modifie une story

### ISSUE THREAD

**Issue by LeoTexier** [dixplo/BigBrainsBoard-Project#32]
Quand on clique sur le bouton qui permet d'accéder à la route /projects/project/stories/{{id du projet}}/edit/{{id de la story}} et une fois sur l'edit de story, quand on clique sur l'un des boutons pour revenir en arrière il y a ces erreurs:

`router.js:1211 Error while processing route: projects.stories.index You must provide param `project_id` to `generate`. Error: You must provide param `project_id` to `generate`.
    at getParam (http://127.0.0.1:4200/assets/vendor.js:69338:13)
    at Array.generate.<computed> (http://127.0.0.1:4200/assets/vendor.js:69426:17)
    at RouteRecognizer.generate$1 [as generate] (http://127.0.0.1:4200/assets/vendor.js:69902:39)
    at PrivateRouter._updateURL (http://127.0.0.1:4200/assets/vendor.js:71959:35)
    at PrivateRouter.finalizeTransition (http://127.0.0.1:4200/assets/vendor.js:71678:14)
    at http://127.0.0.1:4200/assets/vendor.js:71609:21
    at invokeCallback (http://127.0.0.1:4200/assets/vendor.js:72821:17)
    at publish (http://127.0.0.1:4200/assets/vendor.js:72804:9)
    at http://127.0.0.1:4200/assets/vendor.js:67337:53
    at invoke (http://127.0.0.1:4200/assets/vendor.js:65645:16)
logError @ router.js:1211
error @ router.js:1148
triggerEvent @ router.js:1311
triggerEvent @ router.js:175
trigger @ router_js.js:464
finalizeTransition @ router_js.js:1622
(anonymous) @ router_js.js:1539
invokeCallback @ rsvp.js:490
publish @ rsvp.js:473
(anonymous) @ rsvp.js:16
invoke @ backburner.js:335
flush @ backburner.js:226
flush @ backburner.js:423
_end @ backburner.js:957
end @ backburner.js:707
_run @ backburner.js:1012
_join @ backburner.js:986
join @ backburner.js:757
join @ index.js:176
handler @ glimmer.js:8518
(anonymous) @ event_dispatcher.js:348
dispatch @ jquery.js:5237
elemData.handle @ jquery.js:5044
route-recognizer.js:167 Uncaught Error: You must provide param `project_id` to `generate`.
    at getParam (route-recognizer.js:167)
    at Array.generate.<computed> (route-recognizer.js:255)
    at RouteRecognizer.generate$1 [as generate] (route-recognizer.js:731)
    at PrivateRouter._updateURL (router_js.js:1889)
    at PrivateRouter.finalizeTransition (router_js.js:1608)
    at router_js.js:1539
    at invokeCallback (rsvp.js:490)
    at publish (rsvp.js:473)
    at rsvp.js:16
    at invoke (backburner.js:335)`

**Comment by LeoTexier** [comment]
Cependant ces erreurs n'influent pas sur la modification de la story.

**Comment by jcheron** [comment]
Qu'est ce que vous appelez 
>quand on clique sur l'un des boutons pour revenir en arrière il y a ces erreurs

?

**Comment by LeoTexier** [comment]
C'est deux éléments qui permettent d'accéder à la route: 
/projects/project/stories/{{id du projet}}

**Comment by jcheron** [comment]
> C'est deux éléments qui permettent d'accéder à la route:
> /projects/project/stories/{{id du projet}}

Ils n'ont pas une tête de boutons...

**Comment by LeoTexier** [comment]
https://github.com/dixplo/BigBrainsBoard-Project/blob/4d88eb30da73af895332ecdde3c3ac70d0a49db7/app/templates/projects/stories/edit.hbs#L2

https://github.com/dixplo/BigBrainsBoard-Project/blob/4d88eb30da73af895332ecdde3c3ac70d0a49db7/app/templates/projects/stories/edit.hbs#L37

**Comment by LeoTexier** [comment]
Effectivement, problème réglé, merci beaucoup !
